# Generated by Django 3.2.7 on 2021-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repository_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
